[package]
name = "parser"
version = "0.1.0"
authors = [ "" ]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "parser"

[dependencies]
futures = "0.3.26"
form_urlencoded = "1.1.0"
wasmbus-rpc = "0.11.2"
wasmcloud-interface-httpserver = "0.9.0"
serde_json = "1.0.93"
serde = "1.0.152"
async-trait = "0.1.64"
serde_bytes = "0.11.9"

[profile.release]
# Optimize for small code size
lto = true
opt-level = "s"
