search-paths:
  - target/components

#dependencies:
#  downstream: target/components/guest.component.wasm

#instantiations:
#  $input:
#    arguments:
#      guest: guest.component.wasm
#      adapter_guest: adapter_guest.component.wasm

